### PR TITLE
#161087625  dashboard 

### PR DESCRIPTION
**Pull request by jomasim**
# What does this PR do?
Adds product listing cards/container to dashboard
# Description of Tasks to be completed 
- Creating product card/container
- Designing and styling product card/container
- Adding search button to allow searching of products
# How should this be manually tested?
 steps for testing :
    - Create a working folder on your desktop or preferred location.
    - Navigate to your working folder and open a new terminal
    - Type the following ` git clone https://github.com/jomasim/store-manager.git `
    - Navigate to the UI directory and open  home.html in a preferred browser.

# What are the relevant pivotal tracker stories?
Story-ID `#161087625`
# Screenshot
products

### CODE REVIEW

**Comment by sharkdevs** [comment]
great...

**Comment by dev-jey** [comment]
Looks simple and awesome. You can however reduce the size of your products such that a screen will accommodate more products at a time. But its still perfect the way it is. `Just something you can consider`

**Comment by johnwayodi** [comment]
UI is awesome

**Comment by Deekerubo** [comment]
Awesome UI

**Comment by Paulvitalis200** [comment]
Great

**Pull request merged**
