### PR TITLE
#161041881 admin login page 

### PR DESCRIPTION
**Pull request by jomasim**
# What does this PR do?
Creates a login user interface for store admin 
# Description of Tasks to be completed 
- Creating admin landing page 
- Designing and creating login form on admin landing page
# How should this be manually tested?
 steps for testing :
    - Create a working folder on your desktop or preferred location.
    - Navigate to your working folder and open a new terminal
    - Type the following ` git clone https://github.com/jomasim/store-manager.git `
    - Navigate to the UI/admin directory and open  index.html in a preferred browser.

# What are the relevant pivotal tracker stories?
Story-ID `#161041881`
# Screenshot
admin-login

### CODE REVIEW

**Comment by eduhmik** [comment]
Add labels for your input fields

Nice UI

**Comment by Deekerubo** [comment]
Nice interface, you can create a container around the background color such that it doesn't cover the whole page.

**Comment by Allan690** [comment]
Nice ui..make it more intuitive. Weka labels

**Comment by Georgeygigz** [comment]
Page looks good, but you should not raise PR to master, you can change the base branch by clicking edit button close to the pr name then select the base branch

**Comment by sharkdevs** [comment]
Rename the PR name to reflect the story ID rather than the branch

**Comment by andrewhingah** [comment]
Page looks good, but don't raise PR's to master

**Comment by Jnjerry** [comment]
I think you could try not using two darkish colors.Try leaving the background to be just white

**Comment by Paulvitalis200** [comment]
Good and simple.

**Comment by Teatoller** [comment]
> Page looks good, but don't raise PR's to master

I fail to connect why it is that you are doing PR to gh-pages and yet they are connecting to master.
The page looks awesome.

**Pull request merged**
