### PR TITLE
#161146792 cart 

### PR DESCRIPTION
**Pull request by jomasim**
# What does this PR do?
Designing cart page
# Description of Tasks to be completed 
- Creating table for all products added to cart
- Creating summary table for item totals

# How should this be manually tested?
 steps for testing :
    - Create a working folder on your desktop or preferred location.
    - Navigate to your working folder and open a new terminal
    - Type the following ` git clone https://github.com/jomasim/store-manager.git `
    - Navigate to the UI directory and open  cart.html in a preferred browser.

# What are the relevant pivotal tracker stories?
Story-ID `#161146792`
# Screenshot
cart

### CODE REVIEW

**Comment by Jnjerry** [comment]
Add messages to your commits

**Comment by Paulvitalis200** [comment]
Why are there two tables on that page?

**Comment by Teatoller** [comment]
Hello Joma,

The page is done well. An alternative word to 'PRODUCT ID'  could be 'Product Barcode'

Regards
Steven Ennis

**Comment by jomasim** [comment]
> Why are there two tables on that page?
one is for products and detailed desc the other is for summaries and grand totals

**Pull request merged**
