### PR TITLE
#161087625 Designing home/dashboard page 

### PR DESCRIPTION
**Pull request by jomasim**
# What does this PR do?
Creates home page/dashboard with navigation links to  all store app functionalities
# Description of Tasks to be completed 
- Creating store app home page
- Designing and creating home side bar navigation menu
- Designing and creating home top bar navigation menu
# How should this be manually tested?
Steps followed:

- Create a working folder on your desktop or preferred location.
- Navigate to your working folder and open a new terminal
- Type the following ` git clone https://github.com/jomasim/store-manager.git `
- Navigate to the UI directory and open  home.html in a preferred browser.

# What are the relevant pivotal tracker stories?
Story-ID `#161087625`
# Screenshot
home

### CODE REVIEW

**Comment by kwameasiago** [comment]
I would recommend naming your PR using git naming conventions other than that Amazing UI

**Comment by sharkdevs** [comment]
Nice.. Nothing more but for the naming conventions.. Just check that.. Otherwise good job

**Comment by Deekerubo** [comment]
Rename your title using the naming conventions, `#ID Dashbord` ,consider having some links too in the body area, it doesn't have to be blank

**Comment by Paulvitalis200** [comment]
I like where this is heading. Looks good

**Comment by Teatoller** [comment]
Hello Joma,
This looks awesome, and fair interpretation of the ADC challenge 1.
Would you consider adjusting your button to read "Store Attendant" instead of "Seller attendants"?

Regards
Steven Ennis

**Pull request merged**
